# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: Update cgmanifest
on:
    workflow_dispatch:
    pull_request:
      branches:
      - master

defaults:
  run:
    shell: pwsh

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  CGMANIFEST_PATH: ''
  NUGET_PACKAGES: ${{ github.workspace }}\.nuget\packages

jobs:
  update-cgmanifest:
    name: Update cgmanifest
    timeout-minutes: 15
    runs-on: windows-latest
    if: github.repository == 'PowerShell/PowerShell'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache DotNet
        uses: actions/cache@v2
        with:
          path: |
            ~\AppData\Local\Microsoft\dotnet
            ${{ github.workspace }}\.nuget\packages
          key: ${{ runner.os }}-${{ hashFiles('**\DotnetRuntimeMetadata.json') }}-${{ hashFiles('**\nuget.config') }}
      - name: Sync tags
        run: |
          git fetch --prune --unshallow --tags
      - name: Install Ships provider to deal with project.assets.json
        run: |
          Install-Module -Name dotnet.project.assets -force
      - name: Bootstrap
        run: |
          Import-Module ./build.psm1
          Start-PSBootStrap
      - name: Verify cgmanifest is up to date
        run: |
          Import-Module ./build.psm1
          Find-Dotnet
          ./tools/findMissingNotices.ps1
      - name: Upload cgmanifest
        uses: actions/upload-artifact@v2
        if: always() && env.CGMANIFEST_PATH != ''
        with:
          name: cgmanifest
          path: ${{ env.CGMANIFEST_PATH }}
